Task 1.5 Implemented ProductDao
pinkyfox/phoneshop-servlet-api pull request #1
Opened 2019-10-26 19:25 UTC by pinkyfox

2019-10-26 20:15 UTC, Alastifer requested changes

2019-10-26 20:15 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +import java.util.*;
Wildcard для импортов выключи. Лучше, когда видно что ты импортил

2019-10-26 20:15 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +    private Long size = 0L;
Для чего size? Если для генерации ключа, то название поменяй

2019-10-26 20:15 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +    private List<Product> arrayListProductDao;
Лист с названием DAO?

2019-10-26 20:15 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        arrayListProductDao = new ArrayList<>();
Где sample данные из контроллера?

2019-10-26 20:15 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +    }
Stock и price чекать нужно только для листа продуктов (страница PLP - product list page). Пользователь не будет их видеть в листе, но у него должна быть возможность увидеть детали о продукт без стока и цены на странице продукта (PDP - product details page)

2019-10-26 20:15 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                .get()
findFirst() - почитай что он возвращает

2019-10-26 20:15 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                .filter((s) -> s.getId().equals(id) && s.getStock() > 0 && s.getPrice() != null)
Название переменной в лямбда должно быть читаемым. И скобки в лямбде с одной переменной не нужны

2019-10-26 20:15 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                .filter((s) -> s.getStock() > 0 && s.getPrice() != null)
Название переменной в лямбде

2019-10-26 20:15 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        return result.size() == 0 ? null : result;
Если продуктов нет для листа, то принято возвращать просто пустой лист

2019-10-26 20:15 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        size++;
Генерация по полю класса такое себе. Хотя бы бери id последнего продукта из листа и увеличивай просто на 1

2019-10-26 20:15 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        return size;
Кому нужно знать об этом поле? К тому же если оно для генерации юзается

2019-10-26 20:15 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                .filter((s) -> id.compareTo(s.getId()) == 0)
Название переменной в лямбде

2019-10-26 20:15 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                .filter((s) -> id.compareTo(s.getId()) == 0)
Странный способ чекать на равенство

2019-10-26 20:15 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        if (item.isPresent()){
соблюдай форматирование кода

2019-10-26 20:15 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/Product.java
> +import javax.swing.*;
Swing?

2019-10-26 20:15 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/Product.java
> +        this.code = code;
Code и id - это не два ключевых поля случаем? Зачем их два?

2019-10-26 20:15 UTC, Alastifer commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +import com.es.phoneshop.model.product.ArrayListProductDao;
Заимпортил, но никак не юзал

2019-10-26 20:15 UTC, Alastifer commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +
Не нужна пустая строка снизу. Сверху классов нужна

2019-10-26 20:15 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +import static org.junit.Assert.*;
remove wildcard

2019-10-26 20:15 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        productDao.save(new Product("sgs", "Samsung Galaxy S", new BigDecimal(100), usd, 100, "https://raw.githubusercontent.com/andrewosipenko/phoneshop-ext-images/master/manufacturer/Samsung/Samsun
Вынеси setup данных в отдельный метод

2019-10-26 20:15 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        productDao.save(new Product("sgs", "Samsung Galaxy S", new BigDecimal(100), usd, 100, "https://raw.githubusercontent.com/andrewosipenko/phoneshop-ext-images/master/manufacturer/Samsung/Samsun
Так много инфы для тестов не нужно

2019-10-26 20:15 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        assertEquals((Long)13L, productDao.getSize());
Странный каст константы 13

2019-10-26 20:15 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        assertEquals((Long)13L, productDao.getSize());
Вынеси константу в поле

2019-10-26 20:15 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        assertEquals((Long)13L, productDao.getSize());
ты тестишь save, но чекаешь только количество записей, а не из содержание. К тому же чекаешь с помощью поля для генерации ключей, тем самым нарушая сокрытие реализации

2019-10-26 20:15 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    }
А что проверяем то?

2019-10-26 20:15 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    public void deleteNonexistentItemTest(){
Соблюдай форматирование

2019-10-26 20:15 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        assertEquals((Long)2L, productDao.getSize());
Не проверяешь что стало с данными после удаления. Может удалились не 0 и 2, а последние записи

2019-10-26 20:15 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    @Test (expected = java.util.NoSuchElementException.class)
зачем так писать java.util.NoSuchElementException? Читаемость ухудшается

2019-10-26 20:15 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    @Test (expected = java.util.NoSuchElementException.class)
между Test и скобкой убери пробел

2019-10-26 20:15 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        productDao.save(new Product("sgs", "Samsung Galaxy S", null, Currency.getInstance("USD"), 100, "https://raw.githubusercontent.com/andrewosipenko/phoneshop-ext-images/master/manufacturer/Samsu
Зачем id сетать null? Можно же просто другую цифру

2019-10-26 20:15 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    public void getProductWithEmptyPriceFieldTest(){
Форматирование кода

2019-10-26 20:15 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    @Test (expected = java.util.NoSuchElementException.class)
Тоже самое, что и выше

2019-10-26 20:15 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    public void getProductWithIncorrectStockTest(){
Название метода теста должно быть типа returnNullWhenGetProductWithIncorrectStock. Поменяй все названия тестов схожим образом. результатWhenКакое-тоДействие

2019-10-26 20:15 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    public void getProductWithIncorrectStockTest(){
Форматирование кода

2019-10-26 20:15 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        try{
Форматирование кода

2019-10-26 20:15 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    }
Нет проверок, непонятно что тестаешь

2019-10-26 20:15 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    public void getProductTest(){
Форматирование кода

2019-10-26 20:15 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    public void findProductsTest(){
Форматирование кода

2019-10-26 20:15 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    public void findProductNullResultTest(){
Форматирование

2019-10-26 20:15 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        assertTrue(productDao.findProducts() == null);
для проверки на null есть assertNull

2019-10-26 20:25 UTC, pinkyfox commented on src/main/java/com/es/phoneshop/model/product/Product.java
> +import javax.swing.*;
это IDEA.

2019-10-27 13:45 UTC, Alastifer requested changes

2019-10-27 13:45 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        ) {
Не выноси так скобки. Я минуту сидел и думал что ты написал

2019-10-27 13:45 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +            product.setId(UUID.randomUUID().toString());
Сетаешь новый id, когда находишь продукт с таким же id? Зачем?

2019-10-27 13:45 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        Currency usd = Currency.getInstance("USD");
Лучше вынести sample данные в отдельный метод. Конструктор может содержать к примеру подключение БД. А так код становится нечитаемым

2019-10-27 13:45 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/Product.java
>      /** null means there is no price because the product is outdated or new */
Убери комменты из классов. Будем обходиться без них

2019-10-27 13:45 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/Product.java
> +
Много пустых строк

2019-10-27 13:45 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/Product.java
> +    public boolean equals(Object obj) {
Сгенерь идеей

2019-10-27 13:45 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +
Лишние пробелы

2019-10-27 13:45 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +    public synchronized void save(Product product) {
Подумай как должен работать save, если ему передают продукт с уже существующей id

2019-10-27 13:45 UTC, Alastifer commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +        request.setAttribute("products", new ArrayListProductDao());
иии??? создал дао и засетал его???

2019-10-27 13:45 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +
лишние пробелы

2019-10-27 13:45 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    public void saveTest() {
Название не по правилу

2019-10-27 13:45 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +            assertEquals(expectedIds[counter++], product.getId());
Сохранил, достал, проверил id. Не нужно id запихивать в лист. Лучше expectedId1 и expectedId2

2019-10-27 13:45 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        productDao.delete("yuyuqbfqfhuqi");
Не проверяешь, что после удаления несуществующего, все остальные остались как и были

2019-10-27 13:45 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +            assertEquals(expectedIds[counter++], product.getId());
Не юзай массив id

2019-10-27 13:45 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    public void EmptyListWhenFindProducts() {
Именование поправь. У тебя с большой буквы

2019-10-27 13:45 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +                result) {
Не переноси так конструкцию

2019-10-27 18:00 UTC, Alastifer requested changes

2019-10-27 18:00 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +       }
Слетела строка

2019-10-27 18:00 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        else if (arrayListProduct.stream().anyMatch(currentProduct -> product.getId().equals(currentProduct.getId()))) {
else оставляй на строке выше вместе с if

2019-10-27 18:00 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        else if (arrayListProduct.stream().anyMatch(currentProduct -> product.getId().equals(currentProduct.getId()))) {
вынеси проверку в отдельный метод. Будет лучше смотреться и читаться

2019-10-27 18:00 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +            arrayListProduct.set(arrayListProduct.indexOf(getProduct(product.getId()).get()), product);
в отдельный метод поиск позиции вынеси. Слишком громоздко смотрится

2019-10-27 18:00 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        arrayListProduct.add(product);
внеси добавление в if. тогда не придется return из else делать

2019-10-27 18:00 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        arrayListProduct = new ArrayList<>();
sampleInit вызывай в конструкторе. Его нужно было просто в отдельный метод вынести, а не убирать инициализацию sample данных из конструктора

2019-10-27 18:00 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +    public void sampleInit(){
пробел между ) и {

2019-10-27 18:00 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        ((ArrayListProductDao)productDao).sampleInit();
init в конструкторе будет. Не забудь убрать

2019-10-28 06:35 UTC, Alastifer requested changes

2019-10-28 06:35 UTC, Alastifer commented on src/test/java/com/es/phoneshop/web/ProductListPageServletTest.java
> +        servlet.init();
Это в setup

2019-10-28 06:35 UTC, Alastifer commented on src/test/java/com/es/phoneshop/web/ProductListPageServletTest.java
>          when(request.getRequestDispatcher(anyString())).thenReturn(requestDispatcher);
anyString замени на конкретную строку. На ту, что в сервлете

2019-10-28 06:35 UTC, Alastifer commented on src/test/java/com/es/phoneshop/web/ProductListPageServletTest.java
>          verify(requestDispatcher).forward(request, response);
чекай, что в реквесте есть продукты

2019-10-29 07:16 UTC, Alastifer approved these changes

2019-10-29 07:16 UTC, merged